select * from pg_replication_slots;
-- select pg_drop_replication_slot('debezium');

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS "User";

CREATE TABLE "User"
            (
                "id"    uuid              NOT NULL DEFAULT uuid_generate_v4(),
                "email" character varying NOT NULL,
                "name"  character varying,
                CONSTRAINT "UQ_User_email" UNIQUE ("email"),
                CONSTRAINT "PK_User_id" PRIMARY KEY ("id")
            );
            
ALTER TABLE "User" REPLICA IDENTITY FULL;
			
INSERT INTO "User" (email, name)
VALUES ('anmol+1@apg.com', CONCAT('name_', (random() * 1000)::INTEGER::VARCHAR))
ON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name
RETURNING *;


INSERT INTO "User" (email, name)
VALUES ('anmol+2@apg.com', 'name_2');


UPDATE "User"
SET name = 'name_20'
WHERE email = 'anmol+2@apg.com';

UPDATE "User"
SET name = 'name_21'
WHERE email = 'anmol+2@apg.com';


DELETE
FROM "User"
WHERE email = 'anmol+2@apg.com';

select * from "User";

INSERT INTO "User" (email, name)
VALUES ('anmol+3@apg.com', 'name_3');

UPDATE "User"
SET name = 'name_31'
WHERE email = 'anmol+3@apg.com';

INSERT INTO "User" (email, name)
VALUES ('anmol+4@apg.com', 'name_4');

INSERT INTO "User" (email, name)
VALUES ('anmol+5@apg.com', 'name_5');

INSERT INTO "User" (email, name)
VALUES ('anmol+6@apg.com', 'name_6');

INSERT INTO "User" (email, name)
VALUES ('anmol+7@apg.com', 'name_7');

drop table if exists employee;
create table employee 
(
id bigint GENERATED BY DEFAULT AS IDENTITY,
name character varying,
CONSTRAINT "PK_emp_id" PRIMARY KEY ("id")
);

insert into employee(name) values('anmol');

insert into employee(name) values('anmol+1');

insert into employee(name) values('anmol+2');

insert into employee(name) values('anmol+3');

insert into employee(name) values('anmol+4');

insert into employee(name) values('anmol+5');

select * from employee;

select * from employee_2;

create table employee_3
(
id bigint GENERATED BY DEFAULT AS IDENTITY,
name character varying,
CONSTRAINT "PK_emp_id_3" PRIMARY KEY ("id")
);

insert into employee_3(name) values('tom');
insert into employee_3(name) values('tom+1');
insert into employee_3(name) values('tom+2');
insert into employee_3(name) values('tom+3');



alter table employee_3 
add column created_at TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT now() - interval '1 DAY',
alter column created_at SET DEFAULT now();

select * from employee_3;

insert into employee_3(name) values('tom+4');





