services:
   spark:
       build:
           context: .
           dockerfile: ./Dockerfile
       container_name: spark
       hostname: spark
       restart: always
       ports:
            - '8080:8080'
            - '7077:7077'
       environment:
            SPARK_MODE: master
            SPARK_RPC_AUTHENTICATION_ENABLED: 'false'
            SPARK_RPC_ENCRYPTION_ENABLED: 'false'
            SPARK_LOCAL_DIRS: /tmp
            SPARK_WORKER_MEMORY: 2G
            SPARK_WORKER_CORES: 1
            SPARK_WORKER_INSTANCES: 1
            SPARK_WORKER_PORT: 8881
            SPARK_WORKER_WEBUI_PORT: 8081
            SPARK_MASTER_PORT: 7077
            SPARK_MASTER_WEBUI_PORT: 8080
       volumes:
            - "./conf:/opt/bitnami/spark/conf"
            - "./logs:/opt/bitnami/spark/logs"
            - "../data/kafka/out:/out-kafka"
