spark.jars                                           /opt/bitnami/spark/jars/iceberg-spark-runtime-3.4_2.12-1.6.0.jar,/opt/bitnami/spark/jars/iceberg-aws-bundle-1.6.0.jar,/opt/bitnami/spark/jars/lakeformation-2.29.47.jar
spark.sql.extensions                                 org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.spark_catalog                      org.apache.iceberg.spark.SparkSessionCatalog
spark.sql.catalog.spark_catalog.type                 hive
spark.sql.catalog.local                              org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.local.type                         hadoop
spark.sql.catalog.local.warehouse                    /out-kafka/iceberg/warehouse
spark.sql.defaultCatalog                             my_catalog
spark.sql.catalog.my_catalog                         org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.my_catalog.warehouse               s3://ecidtpl-test-3d6e38d3cf5dc557/anmol/kafka/out/apg_test
spark.sql.catalog.my_catalog.type                    glue
spark.sql.catalog.my_catalog.io-impl                 org.apache.iceberg.aws.s3.S3FileIO
spark.sql.lakeFormation.enabled                      true