spark.jars                                           /opt/bitnami/spark/jars/aws-glue-datacatalog-spark-client-3.4.0-SNAPSHOT.jar
spark.hive.metastore.client.factory.class            com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
spark.hive.imetastoreclient.factory.class            com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory
